### ISSUE TITLE
European Portuguese version a bit too sweary?

### ISSUE THREAD

**Issue by GilOliveira** [neatnik/asshole.fyi#21]
I understand the philosophy of this project and appreciate its bluntness, but the European Portuguese translation (pt) seems a bit too much sweary... "c***ão" is maybe one of the harshest Portuguese swear words, I think "otário" would be a much closer translation of "asshole" as it is more slang than swear. As it is I don't think I would be comfortable sending this link to anyone, no matter how much they "fit the description" Specially considering that the Brazilian Portuguese version goes in the absolute opposite direction with "idiota" which almost seems overly polite in comparison (however, it is the Google Translate recommended word in Portuguese for "asshole").

I think "otário" strikes a much better balance, seems a closer translation to the intended feeling of the project, and it it's a pretty common slang to use in Portugal.

Tagging the contributor @maique.

PS: looking back this is probably the weirdest issue I've ever submitted 😅

**Comment by newbold** [comment]
@GilOliveira What would the updated version look like? “ Não sejas um otário, e não toleres otários”, or something else? (Sorry, I know virtually no Portuguese so I have no idea how to correctly form a plural of a noun, heh.)

**Comment by GilOliveira** [comment]
> "Não sejas um otário, e não toleres otários"

@newbold Spot on!

**Comment by newbold** [comment]
All set. Thanks!
